"""Application constants."""
KEYWORDS = [
    "behavioral interview tips",
    "system design interview framework",
    "Stripe system design interview",
    "Agentic AI engineering interview",
    "LeetCode patterns for interviews",
    "machine learning engineering interview",
    "technical interview preparation",
    "software engineer job market 2026",
    "STAR method behavioral questions",
    "LLM evaluation interview questions",
    "tech layoffs job search",
    "Google interview prep",
    "Amazon leadership principles interview",
    "bootcamp grad first tech job",
    "mock interview practice",
    "system design scalability",
    "FAANG interview process",
    "agent framework comparison LangGraph CrewAI",
    "interview failure recovery",
    "senior engineer interview tips",
    "backend system architecture interview",
    "frontend react interview questions",
    "DevOps CI/CD interview questions",
    "blockchain smart contract interview",
    "full stack web development interview",
    "database internals interview questions",
    "cybersecurity network protocol interview",
    "data structures algorithms product based companies",
    "high level design distributed systems",
    "low level design object oriented programming",
    "SDE-2 software engineer interview",
    "tool calling JSON schema LLM interview",
    "agentic system design mock interview",
    "Microsoft Azure system design interview",
    "Apple hardware software interview",
    "Uber geospatial microservices interview",
    "Airbnb cross functional interview",
    "PayPal transaction database interview",
    "salary negotiation tech offer",
    "H1B OPT software engineer jobs",
    "coding interview dynamic programming",
    "system design load balancing",
]

ULTIMATE_FALLBACK_DEFAULTS = {
    'IMAGE_MODEL': '@cf/black-forest-labs/flux-1-schnell',
    'CONTENT_MODEL': 'openai/gpt-oss-120b:free,nvidia/nemotron-3-super-120b-a12b:free,z-ai/glm-4.5-air:free',
    'OPENROUTER_API': '',
    'CLOUDFLARE_ACCOUNT_ID': '',
    'CLOUDFLARE_API_TOKEN': '',
    'GSHEET_ID': '',
    'IMGBB_API_KEY': '',
    'IMAGE_STORAGE_PROVIDER': 'cloudinary',
    'CLOUDINARY_CLOUD_NAME': '',
    'CLOUDINARY_API_KEY': '',
    'CLOUDINARY_API_SECRET': '',
    'POST_COUNT': '3',
    'LLM_CALL_DELAY_SECONDS': '15',
}




